### ISSUE TITLE
Ventus: an RVV-based General Purpose GPU Design and Implementation理论算力的计算方式

### ISSUE THREAD

**Issue by wcq22** [THU-DSP-LAB/ventus-gpgpu#71]
请问能否详细介绍一下Ventus: an RVV-based General Purpose GPU Design and Implementation文章同提到的：
 16SM-16warp-16lane version with Tensor Core 10MHz theoretical peak performance is 5GFlops FP32 on normal lanes and 5GFlops FP32 on Tensor Core.
其中理论算力如何计算？另是否normal lanes+Tensor Core算力一共10GFlops?
谢谢

**Comment by reoLantern** [comment]
$Tensor\ Core: 5GFLOPs=10MHz\times 16 SM \times (2\times 4\times 2)\times 2$

This is because the Chisel version of the tensor core design at that time only supported two configurations: 8 lanes and 32 lanes. When configured with 16 lanes, the tensor core still operated in the 8-lane configuration of 2×4×2 (with matrix A as 2×4 and matrix B as 4×2, both in FP32). As a result, the bandwidth between the tensor core and the pipeline could not be fully utilized under this configuration.

In practical scenarios, NVIDIA always fixes the number of lanes in a warp to 32, and the tensor core configuration is aligned with this design. We have adopted this approach in the latest version, enabling the tensor core only when the number of lanes is set to 32.
