### ISSUE TITLE
make init failed.

### ISSUE THREAD

**Issue by diantaowang** [THU-DSP-LAB/ventus-gpgpu#72]
make init failed. 

```c
git submodule update --init --recursive --progress
fatal: No url found for submodule path 'dependencies/Membox2.Scala' in .gitmodules
make: *** [Makefile:4: init] Error 128
```

There is no url for Membox2.Scala in .gitmodules. And the Membox2.Scala can't open in web page.

**Comment by reoLantern** [comment]
This issue occurred because the ownership of the `Membox` submodule was recently transferred (from a personal account to `THU-DSP-LAB`). I will fix this problem within a few hours. In the meantime, you can temporarily resolve it by updating the link to:  
[https://github.com/THU-DSP-LAB/Membox2.Scala](https://github.com/THU-DSP-LAB/Membox2.Scala).

**Comment by reoLantern** [comment]
My mistake. The submodule `Membox2.scala` was not used in the `master` branch and was mistakenly added earlier. I have now removed it in commit 95a592c. Thank you for catching that!
